cc_test(
    name = "basic_tests",
    srcs = ["basic_tests.cc"],
    deps = ["//:variant"]
)

cc_test(
    name = "visitor_test",
    srcs = ["visitor_test.cc"],
    deps = ["//:variant"]
)

cc_test(
    name = "crash_test",
    srcs = ["crash_test.cc"],
    deps = ["//:variant"]
)
